import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, serverTimestamp, updateDoc } from "firebase/firestore";
import { auth, db } from "../firebase";
import { createNotification, sendPushNotification } from "./notificationService";
import { socket } from "../utils/socket";
import { getUser } from "../utils/auth";

const tasksRef=collection(db,"tasks"),usersRef=collection(db,"powerhouse_users");
let cache=null,cacheAt=0,pending=null;
const now=()=>new Date().toISOString();
const clean=v=>v&&typeof v.toDate==="function"?v.toDate().toISOString():Array.isArray(v)?v.map(clean):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)])):v;
const strip=t=>{const x={...(t||{})};["attachments","files","media","file","upload","uploads","evidence","images","photos","documents"].forEach(k=>delete x[k]);return x};
export const isTaskPath=(path="")=>/(^|\/)(tasks?|my-tasks?|task-view|task-completion|task-report)(\/|$)|task/.test(String(path||"").toLowerCase());
const raw=s=>strip({id:s.id,...clean(s.data()||{})});
const n=t=>{const x=Number(t?.task_number??t?.display_id??t?.public_id);return Number.isInteger(x)&&x>0?x:null};
const view=t=>{const x=strip(t),num=n(x);return {...x,id:num??x.id,firestore_id:x.id,task_number:num!=null?String(num):x.task_number,display_id:num!=null?String(num):x.display_id,public_id:num??x.public_id}};
export const invalidateTaskCache=()=>{cache=null;cacheAt=0};
export const invalidateStaffCache=()=>{};
async function all(){if(cache&&Date.now()-cacheAt<1500)return cache;if(pending)return pending;pending=getDocs(tasksRef).then(s=>s.docs.map(raw)).then(x=>{cache=x;cacheAt=Date.now();return x}).finally(()=>pending=null);return pending}
const identities=()=>[getUser()?.id,getUser()?.numericId,getUser()?.uid,getUser()?.firebaseUid,getUser()?.user_id,auth.currentUser?.uid].filter(v=>v!=null&&String(v).trim()).map(String);
const taskAssignedIds=t=>[...(Array.isArray(t?.assigned_user_ids)?t.assigned_user_ids:[]),...(Array.isArray(t?.user_ids)?t.user_ids:[]),...(Array.isArray(t?.assigned_staff_ids)?t.assigned_staff_ids:[]),t?.user_id,t?.assigned_user_id,t?.assignedTo].filter(v=>v!=null&&typeof v!=="object"&&String(v).trim()).map(String);
const mine=(t,ids)=>taskAssignedIds(t).some(x=>ids.includes(x));
async function find(id){const key=String(id??"");const t=(await all()).find(x=>[x.id,x.firestore_id,x.task_number,x.display_id,x.public_id].some(v=>String(v)===key));if(t)return {id:t.firestore_id||t.id,ref:doc(db,"tasks",t.firestore_id||t.id),data:()=>t};const d=await getDoc(doc(db,"tasks",key));return d.exists()?d:null}
async function payload(data){let x={...(data||{})};if(typeof FormData!=="undefined"&&data instanceof FormData){x={};for(const [k,v] of data.entries()){if(typeof File!=="undefined"&&v instanceof File)continue;const key=k.replace(/\[\]$/,""),old=x[key];x[key]=old===undefined?v:Array.isArray(old)?[...old,v]:[old,v]}}return strip(x)}
const status=v=>{v=String(v||"").toLowerCase().replace(/_/g," ");return ["accepted","in progress","running"].includes(v)?"In Progress":["complete","completed","done"].includes(v)?"Completed":v==="rejected"?"Rejected":"Pending"};
const staffIdCandidates=s=>[s?.id,s?.user_id,s?.uid,s?.firebaseUid,s?.firebase_uid,s?.numericId,s?.employeeID,s?.employee_id,s?.employeeId].filter(v=>v!=null&&String(v).trim()).map(v=>String(v));
const staffName=s=>String(s?.name||s?.full_name||s?.fullName||s?.displayName||s?.display_name||s?.email||"").trim();
async function loadStaff(){try{return (await getDocs(usersRef)).docs.map(s=>({id:s.id,...clean(s.data()||{})}))}catch(e){console.warn("Staff lookup failed",e);return []}}
function staffMap(staff){const m=new Map();staff.forEach(s=>staffIdCandidates(s).forEach(id=>{if(!m.has(id))m.set(id,s)}));return m}
function normalizeAssigned(task,staff){const ids=[...new Set(taskAssignedIds(task))];const byId=staffMap(staff||[]);const existing=Array.isArray(task?.assigned_users)?task.assigned_users.filter(Boolean):[];const names0=Array.isArray(task?.assigned_staff_names)?task.assigned_staff_names:[];const assigned=ids.map((id,i)=>{const current=existing.find(u=>staffIdCandidates(u).includes(id));const u=current||byId.get(id)||null;const name=staffName(current)||staffName(u)||String(names0[i]||"").trim();return {id:userIdFor(u,id),user_id:id,uid:u?.uid||u?.firebaseUid||current?.uid||null,name,email:u?.email||current?.email||"",role:u?.role||current?.role||"",profile_pic:u?.profile_pic||u?.profilePic||current?.profile_pic||null}});return {ids,assigned,names:assigned.map(x=>x.name).filter(Boolean)}}
function userIdFor(u,fallback){return u?.id||u?.user_id||u?.numericId||fallback}
async function notify(ids,title,body,taskId,type="task_update",priority="High"){const recipients=[...new Set(ids.map(String).filter(Boolean))];if(!recipients.length)return;const results=await Promise.allSettled(recipients.map(uid=>createNotification(uid,{title,body,type,route:`/task-view/${taskId}`,taskId,priority})));await Promise.allSettled(recipients.map((uid,index)=>sendPushNotification({title,body,route:`/task-view/${taskId}`,taskId,userIds:[uid],notificationId:results[index].status==="fulfilled"?results[index].value:`task-${taskId}-${type}-${Date.now()}-${index}`,priority})))}
export async function listTasks(){return (await all()).map(view).sort((a,b)=>(n(b)||0)-(n(a)||0))}
export async function listMyTasks(userId){const ids=[...new Set([...identities(),userId].filter(Boolean).map(String))];return (await all()).filter(t=>mine(t,ids)).map(view).sort((a,b)=>new Date(b.updated_at||b.created_at||0)-new Date(a.updated_at||a.created_at||0))}
export const listUserTasks=listMyTasks;

async function enrichTaskForReport(task){if(!task||typeof task!=="object")return task;const staff=await loadStaff();const {ids,assigned,names}=normalizeAssigned(task,staff);const reports=[];try{const snaps=await getDocs(collection(db,"task_completion_reports"));const key=String(task.task_number??task.display_id??task.public_id??task.id);snaps.docs.map(raw).filter(r=>String(r.task_id??r.taskId??r.task_number??r.id??"")===key).forEach(r=>reports.push(r))}catch(e){console.warn("Task report completion lookup failed",e)}const hasCompletion=reports.length>0||Boolean(task.completion_report_id)||["completed","complete","done"].includes(String(task.status||"").toLowerCase());const firstName=names[0]||staffName(task.assignedUser)||task.assignedToName||task.assigned_to_name||task.userName||task.staffName||task.staff_name||task.assigned_to||"";return {...task,assigned_user_ids:ids,user_ids:Array.isArray(task.user_ids)?task.user_ids:ids,user_id:task.user_id||ids[0]||null,assigned_user_id:task.assigned_user_id||ids[0]||null,assigned_users:assigned,assignedUser:assigned[0]||task.assignedUser||null,assigned_staff_names:names,assignedToName:firstName||null,assigned_to_name:firstName||null,userName:firstName||null,staffName:firstName||null,staff_name:firstName||null,assigned_to:names.join(", ")||firstName||null,completion_reports:reports.length?reports:(Array.isArray(task.completion_reports)?task.completion_reports:[]),latest_completion:reports[0]||task.latest_completion||null,has_completion_report:hasCompletion,status:hasCompletion?"Completed":status(task.status),executionStatus:hasCompletion?"COMPLETED":task.executionStatus,execution_status:hasCompletion?"Completed":task.execution_status,completeWorkStatus:hasCompletion?"SUBMITTED":task.completeWorkStatus,complete_work_status:hasCompletion?"SUBMITTED":task.complete_work_status,isCompleted:hasCompletion||Boolean(task.isCompleted)}}
export async function getTask(id){const d=await find(id);if(!d)throw new Error("Task not found.");return view(await enrichTaskForReport(raw(d)))}

export async function assignTask(data){const p=await payload(data);const ids=[...(Array.isArray(p.assigned_user_ids)?p.assigned_user_ids:Array.isArray(p.user_ids)?p.user_ids:Array.isArray(p.assigned_staff_ids)?p.assigned_staff_ids:[p.user_id??p.assigned_user_id??p.assignedTo]).filter(v=>v!=null&&String(v).trim())].map(String);if(!ids.length)throw new Error("Please select at least one staff member.");const staff=await loadStaff();const {assigned,names}=normalizeAssigned({assigned_user_ids:ids,assigned_users:p.assigned_users,assigned_staff_names:p.assigned_staff_names},staff);const existing=await all(),used=new Set(existing.map(n).filter(Boolean));let num=1;while(used.has(num))num++;const stamp=now();const firstName=names[0]||staffName(p.assignedUser)||p.assignedToName||p.assigned_to_name||p.userName||p.staffName||p.staff_name||p.assigned_to||"";const task=strip({...p,task_number:String(num),display_id:String(num),public_id:num,assigned_user_ids:ids,user_ids:ids,assigned_staff_ids:ids,user_id:ids[0],assigned_user_id:ids[0],assigned_users:assigned,assigned_staff_names:names,assignedToName:firstName||null,assigned_to_name:firstName||null,userName:firstName||null,staffName:firstName||null,staff_name:firstName||null,assigned_to:names.join(", ")||firstName||null,status:status(p.status),assignment_cycle:1,assignment_count:1,created_at:stamp,updated_at:stamp,createdAt:serverTimestamp()});const r=await addDoc(tasksRef,task);invalidateTaskCache();const taskTitle=String(task.title||task.task_title||task.name||`Task #${num}`),taskPriority=String(task.priority||task.type||"High");void notify(ids,"New Task Assigned",`${taskTitle} • Priority: ${taskPriority}`,num,"task_assigned",taskPriority);try{socket.emit("taskAssigned",{taskId:num,userIds:ids,status:task.status,task:view({...task,id:r.id}),title:"New Task Assigned",body:`${taskTitle} • Priority: ${taskPriority}`,route:`/task-view/${num}`})}catch{}return view({...task,id:r.id})}
export async function updateTask(id,data){const d=await find(id);if(!d)throw new Error("Task not found.");const old=raw(d),p=await payload(data),next=strip({...p,updated_at:now()});if(p.status!==undefined)next.status=status(p.status);await updateDoc(d.ref,next);cache=cache?.map(t=>t.id===old.id?{...t,...next}:t)||null;cacheAt=Date.now();const updated={...old,...next},ids=taskAssignedIds(updated);if(next.status)void notify(ids,"Task Updated",`Task #${n(old)??old.id} status: ${next.status}`,n(old)??old.id);try{socket.emit("taskUpdate",{taskId:n(old)??old.id,status:next.status||old.status,userIds:ids,task:view(updated)})}catch{}return view(updated)}
export const updateTaskStatus=(id,data)=>updateTask(id,typeof data==="object"?data:{status:data});
export async function completeTask(id,data={}){const completedAt=now();return updateTask(id,{...(await payload(data)),status:"Completed",completed_at:completedAt,completed_by:(getUser()?.name||auth.currentUser?.email||"User"),completion_submitted_at:completedAt,completion_report_status:"Completed",complete_work_status:"SUBMITTED",execution_status:"Completed",executionStatus:"COMPLETED",completeWorkStatus:"SUBMITTED",isCompleted:true,completedAt:completedAt})}
export async function deleteTask(id){const d=await find(id);if(!d)throw new Error("Task not found.");const old=raw(d),num=n(old)??old.id,ids=taskAssignedIds(old);await deleteDoc(d.ref);invalidateTaskCache();void notify(ids,"Task Deleted",`Task #${num} has been removed.`,num,"task_deleted");try{socket.emit("taskDeleted",{taskId:num,userIds:ids})}catch{}return true}
export function subscribeTasks(callback,{userId}={}){const ids=userId==null?[]:[...new Set([...identities(),userId].filter(Boolean).map(String))];return onSnapshot(tasksRef,s=>{const rows=s.docs.map(raw);cache=rows;cacheAt=Date.now();const filtered=ids.length?rows.filter(t=>mine(t,ids)):rows;callback(filtered.map(view).sort((a,b)=>(n(b)||0)-(n(a)||0)))},e=>console.warn("Task realtime listener failed",e))}
export const subscribeMyTasks=(callback,userId)=>subscribeTasks(callback,{userId});
export async function createCompletionReport(data){const p=await payload(data),submittedAt=now(),taskId=p.task_id??p.taskId??p.id??null;const report=strip({...p,status:"Completed",work_status:"Completed",report_status:"Completed",complete_work_status:"SUBMITTED",created_at:serverTimestamp(),submitted_at:submittedAt,completed_at:submittedAt});const result=await addDoc(collection(db,"task_completion_reports"),report);if(taskId!=null){try{await completeTask(taskId,{completion_report_id:result.id,completion_report_status:"Completed",complete_work_status:"SUBMITTED",execution_status:"Completed"})}catch(error){console.warn("Completion report created but task sync failed:",error)}}invalidateTaskCache();return result}
const enrichDashboardTask=(task,byId)=>{const ids=[...new Set(taskAssignedIds(task))],existing=Array.isArray(task?.assigned_users)?task.assigned_users.filter(Boolean):[];const resolved=ids.map((id,i)=>{const current=existing.find(u=>staffIdCandidates(u).includes(id)),staff=current||byId.get(id)||null,name=staffName(current)||staffName(staff)||task?.assigned_staff_names?.[i]||"";return {id,user_id:id,uid:staff?.uid||staff?.firebaseUid||current?.uid||null,name,email:staff?.email||current?.email||"",role:staff?.role||current?.role||"",profile_pic:staff?.profile_pic||staff?.profilePic||current?.profile_pic||null,employee_id:staff?.employeeID||staff?.employee_id||current?.employee_id||""}}),names=resolved.map(x=>x.name).filter(Boolean);return {...task,assigned_user_ids:ids,user_ids:Array.isArray(task?.user_ids)?task.user_ids:ids,user_id:task?.user_id||ids[0]||null,assigned_users:resolved,assigned_staff_names:names,assigned_staff_emails:resolved.map(x=>x.email).filter(Boolean),assigned_staff_roles:resolved.map(x=>x.role).filter(Boolean),assignedToName:names[0]||task?.assignedToName||null,staff_name:names[0]||task?.staff_name||null,profile_pic:resolved[0]?.profile_pic||task?.profile_pic||null}}
export async function activityStats(){const rows=await all(),staff=await loadStaff(),byId=staffMap(staff),activities=rows.map(t=>view(enrichDashboardTask(t,byId))),total=activities.length,pendingCount=activities.filter(t=>status(t.status)==="Pending").length,inProgress=activities.filter(t=>status(t.status)==="In Progress").length,completed=activities.filter(t=>status(t.status)==="Completed").length,rejected=activities.filter(t=>status(t.status)==="Rejected").length;return {staffCount:staff.length,taskCount:total,pendingCount,inProgressCount:inProgress,completedCount:completed,rejectedCount:rejected,activities,total,pending:pendingCount,active:inProgress,running:inProgress,in_progress:inProgress,inProgress,completed,closed:completed,rejected,open:total-completed-rejected,total_tasks:total,pending_tasks:pendingCount,in_progress_tasks:inProgress,completed_tasks:completed,rejected_tasks:rejected}};
