import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, serverTimestamp, updateDoc } from "firebase/firestore";
import { auth, db } from "../firebase";
import { createNotification, sendPushNotification } from "./notificationService";
import { socket } from "../utils/socket";
import { getUser } from "../utils/auth";
const tasksRef=collection(db,"tasks"),usersRef=collection(db,"powerhouse_users");
let cache=null,cacheAt=0,pending=null; const now=()=>new Date().toISOString();
const clean=v=>v&&typeof v.toDate==="function"?v.toDate().toISOString():Array.isArray(v)?v.map(clean):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)])):v;
const strip=t=>{const x={...(t||{})};["attachments","files","media","file","upload","uploads","evidence","images","photos","documents"].forEach(k=>delete x[k]);return x};
export const isTaskPath=(path="")=>{const p=String(path||"").toLowerCase();return /(^|\/)(tasks?|my-tasks?|task-view|task-completion|task-report)(\/|$)|task/.test(p)};
const raw=s=>strip({id:s.id,...clean(s.data()||{})}); const n=t=>{const x=Number(t?.task_number??t?.display_id??t?.public_id);return Number.isInteger(x)&&x>0?x:null};
const view=t=>{const x=strip(t),num=n(x);return {...x,id:num??x.id,firestore_id:x.id,task_number:num!=null?String(num):x.task_number,display_id:num!=null?String(num):x.display_id,public_id:num??x.public_id}};
export const invalidateTaskCache=()=>{cache=null;cacheAt=0}; export const invalidateStaffCache=()=>{};
async function all(){if(cache&&Date.now()-cacheAt<1500)return cache;if(pending)return pending;pending=getDocs(tasksRef).then(s=>s.docs.map(raw)).then(x=>{cache=x;cacheAt=Date.now();return x}).finally(()=>pending=null);return pending}
const identities=()=>[getUser()?.id,getUser()?.numericId,getUser()?.uid,getUser()?.firebaseUid,getUser()?.user_id,auth.currentUser?.uid].filter(v=>v!=null&&String(v).trim()).map(String);
const mine=(t,ids)=>[...(t.assigned_user_ids||[]),...(t.user_ids||[]),...(t.assigned_staff_ids||[]),t.user_id].filter(Boolean).map(String).some(x=>ids.includes(x));
async function find(id){const key=String(id??"");let t=(await all()).find(x=>[x.id,x.firestore_id,x.task_number,x.display_id,x.public_id].some(v=>String(v)===key));if(t)return {id:t.firestore_id||t.id,ref:doc(db,"tasks",t.firestore_id||t.id),data:()=>t};const d=await getDoc(doc(db,"tasks",key));return d.exists()?d:null}
async function payload(data){let x={...(data||{})};if(typeof FormData!=="undefined"&&data instanceof FormData){x={};for(const [k,v] of data.entries()){if(typeof File!=="undefined"&&v instanceof File)continue;const key=k.replace(/\[\]$/,""),val=x[key];x[key]=val===undefined?v:Array.isArray(val)?[...val,v]:[val,v]}}return strip(x)}
const status=v=>{v=String(v||"").toLowerCase().replace(/_/g," ");return ["accepted","in progress","running"].includes(v)?"In Progress":["complete","completed","done"].includes(v)?"Completed":v==="rejected"?"Rejected":"Pending"};
async function notify(ids,title,body,taskId,type="task_update"){await Promise.allSettled([...new Set(ids.map(String))].map(async uid=>{const notificationId=await createNotification(uid,{title,body,type,route:`/task-view/${taskId}`,taskId,priority:"high"});await sendPushNotification({title,body,route:`/task-view/${taskId}`,taskId,userIds:[uid],notificationId,priority:"high"})}))}
export async function listTasks(){return (await all()).map(view).sort((a,b)=>(n(b)||0)-(n(a)||0))}
export async function listMyTasks(userId){const ids=[...new Set([...identities(),userId].filter(Boolean).map(String))];return (await all()).filter(t=>mine(t,ids)).map(view).sort((a,b)=>new Date(b.updated_at||b.created_at||0)-new Date(a.updated_at||a.created_at||0))}
export const listUserTasks=listMyTasks;
export async function getTask(id){const d=await find(id);if(!d)throw new Error("Task not found.");return view(raw(d))}
export async function assignTask(data){const p=await payload(data),ids=[...(Array.isArray(p.assigned_user_ids)?p.assigned_user_ids:Array.isArray(p.user_ids)?p.user_ids:[p.user_id]).filter(Boolean)].map(String);if(!ids.length)throw new Error("Please select at least one staff member.");const existing=await all(),used=new Set(existing.map(n).filter(Boolean));let num=1;while(used.has(num))num++;const stamp=now(),task=strip({...p,task_number:String(num),display_id:String(num),public_id:num,assigned_user_ids:ids,user_ids:ids,user_id:ids[0],status:status(p.status),assignment_cycle:1,assignment_count:1,created_at:stamp,updated_at:stamp,createdAt:serverTimestamp()});const r=await addDoc(tasksRef,task);invalidateTaskCache();void notify(ids,"New Task Assigned",`Task #${num} has been assigned to you.`,num,"task_assigned");try{socket.emit("taskAssigned",{taskId:num,userIds:ids,status:task.status,task:view({...task,id:r.id}),title:"New Task Assigned",body:`Task #${num} has been assigned to you.`,route:`/task-view/${num}`})}catch{}return view({...task,id:r.id})}
export async function updateTask(id,data){const d=await find(id);if(!d)throw new Error("Task not found.");const old=raw(d),p=await payload(data),next=strip({...p,updated_at:now()});if(p.status!==undefined)next.status=status(p.status);await updateDoc(d.ref,next);cache=cache?.map(t=>t.id===old.id?{...t,...next}:t)||null;cacheAt=Date.now();const updated={...old,...next},ids=[...(old.assigned_user_ids||old.user_ids||[])].map(String);if(next.status)void notify(ids,"Task Updated",`Task #${n(old)??old.id} status: ${next.status}`,n(old)??old.id);try{socket.emit("taskUpdate",{taskId:n(old)??old.id,status:next.status||old.status,userIds:ids,task:view(updated)})}catch{}return view(updated)}
export const updateTaskStatus=(id,data)=>updateTask(id,typeof data==="object"?data:{status:data});
export async function completeTask(id,data={}){return updateTask(id,{...(await payload(data)),status:"Completed",completed_at:now(),completed_by:(getUser()?.name||auth.currentUser?.email||"User")})}
export async function deleteTask(id){const d=await find(id);if(!d)throw new Error("Task not found.");const old=raw(d),num=n(old)??old.id,ids=[...(old.assigned_user_ids||old.user_ids||[])].map(String);await deleteDoc(d.ref);invalidateTaskCache();void notify(ids,"Task Deleted",`Task #${num} has been removed.`,num,"task_deleted");try{socket.emit("taskDeleted",{taskId:num,userIds:ids})}catch{}return true}
export function subscribeTasks(callback,{userId}={}){const ids=userId==null?[]:[...new Set([...identities(),userId].filter(Boolean).map(String))];return onSnapshot(tasksRef,s=>{const rows=s.docs.map(raw);cache=rows;cacheAt=Date.now();const filtered=ids.length?rows.filter(t=>mine(t,ids)):rows;callback(filtered.map(view).sort((a,b)=>(n(b)||0)-(n(a)||0)))},e=>console.warn("Task realtime listener failed",e))}
export const subscribeMyTasks=(callback,userId)=>subscribeTasks(callback,{userId});
export async function createCompletionReport(data){const p=await payload(data);return addDoc(collection(db,"task_completion_reports"),strip({...p,created_at:serverTimestamp(),completed_at:now()}))}
export async function activityStats(){const rows=await all();let staff=[];try{staff=(await getDocs(usersRef)).docs.map(s=>clean(s.data()||{}))}catch(e){console.warn("Dashboard staff read failed",e)}const total=rows.length,pendingCount=rows.filter(t=>status(t.status)==="Pending").length,inProgress=rows.filter(t=>status(t.status)==="In Progress").length,completed=rows.filter(t=>status(t.status)==="Completed").length,rejected=rows.filter(t=>status(t.status)==="Rejected").length;return {staffCount:staff.length,taskCount:total,pendingCount,inProgressCount:inProgress,completedCount:completed,rejectedCount:rejected,activities:rows.map(view),total,pending:pendingCount,active:inProgress,running:inProgress,in_progress:inProgress,inProgress,completed,closed:completed,rejected,open:total-completed-rejected,total_tasks:total,pending_tasks:pendingCount,in_progress_tasks:inProgress,completed_tasks:completed,rejected_tasks:rejected};}
