import React,{useEffect,useState}from"react";
import{collection,doc,limit,onSnapshot,orderBy,query,serverTimestamp,setDoc}from"firebase/firestore";
import{AlertTriangle,Bell,BellRing,CheckCircle2,Clock3,Flame,RefreshCw,Save,ShieldAlert,Volume2,VolumeX,X}from"lucide-react";
import{db}from"../firebase";
import{enablePushNotifications}from"../services/notificationService";
const SREF=doc(db,"powerhouse_settings","alerts"),AREF=doc(db,"powerhouse_alert_state","current");
const DEF={enabled:true,pushEnabled:true,silent:false,lowDieselThreshold:3000,repeatMinutes:30,alarmDurationSeconds:30,alarmTone:"chime",customSoundUrl:""};
const TONES=[{id:"chime",name:"Professional Chime",desc:"Clear operational signal"},{id:"gentle",name:"Gentle Monitor",desc:"Softer monitoring signal"},{id:"pulse",name:"Attention Pulse",desc:"Urgent repeating signal"},{id:"custom",name:"Custom Sound",desc:"MP3 / OGG / WAV URL"}];
const REPEATS=[1,5,10,15,30,60],DURS=[20,25,30],num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function ring(t){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),b=c.currentTime+.02,n=t==="gentle"?[[660,0,.3],[880,.35,.3],[784,.75,.3]]:[[784,0,.2],[1046,.28,.23],[880,.62,.23]];n.forEach(([f,o,d])=>{const a=c.createOscillator(),g=c.createGain();a.type="sine";a.frequency.value=f;g.gain.setValueAtTime(.0001,b+o);g.gain.exponentialRampToValueAtTime(.55,b+o+.02);g.gain.exponentialRampToValueAtTime(.0001,b+o+d);a.connect(g);g.connect(c.destination);a.start(b+o);a.stop(b+o+d+.03)});setTimeout(()=>c.close().catch(()=>{}),1600)}catch{}}
export default function DieselAlertProV2(){const[s,setS]=useState(DEF),[saved,setSaved]=useState(DEF),[stock,setStock]=useState(null),[active,setActive]=useState(null),[events,setEvents]=useState([]),[saving,setSaving]=useState(false),[push,setPush]=useState("idle"),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[tester,setTester]=useState(false),[testTitle,setTestTitle]=useState("LOW DIESEL STOCK"),[testBody,setTestBody]=useState("Diesel stock is below the configured safety level.");
useEffect(()=>onSnapshot(SREF,x=>{const d=x.exists()?x.data():{};const n={...DEF,...d,lowDieselThreshold:Math.max(0,num(d.lowDieselThreshold??d.lowStockLevel,3000)),repeatMinutes:Math.max(1,num(d.repeatMinutes??d.repeatIntervalMinutes,30)),alarmDurationSeconds:Math.min(30,Math.max(20,num(d.alarmDurationSeconds,30)))};setS(n);setSaved(n)},e=>setErr(e.message)),[]);
useEffect(()=>onSnapshot(query(collection(db,"entries"),orderBy("createdAt","desc"),limit(1)),x=>{const d=x.docs[0]?.data()||{};setStock(num(d.currentStock??d.stock??d.remainingStock??d.closingStock))},e=>setErr(e.message)),[]);
useEffect(()=>onSnapshot(AREF,x=>setActive(x.exists()&&x.data()?.active!==false?x.data():null),e=>setErr(e.message)),[]);
useEffect(()=>onSnapshot(query(collection(db,"powerhouse_alert_events"),orderBy("createdAt","desc"),limit(12)),x=>setEvents(x.docs.map(d=>({id:d.id,...d.data()}))),()=>{}),[]);
const low=stock!==null&&s.enabled&&stock<s.lowDieselThreshold,changed=JSON.stringify(s)!==JSON.stringify(saved);
const save=async()=>{setSaving(true);setErr("");try{const n={...s,lowDieselThreshold:Math.max(0,num(s.lowDieselThreshold)),repeatMinutes:Math.max(1,Math.round(num(s.repeatMinutes,30))),alarmDurationSeconds:Math.min(30,Math.max(20,Math.round(num(s.alarmDurationSeconds,30)))),updatedAt:serverTimestamp()};await setDoc(SREF,n,{merge:true});setSaved({...n,updatedAt:undefined});setS({...n,updatedAt:undefined});setMsg("Global diesel alert settings saved successfully.")}catch(e){setErr(e.message)}finally{setSaving(false)}};
const enable=async()=>{setPush("loading");setErr("");try{await enablePushNotifications();setPush("enabled");setMsg("Push notifications enabled on this device.")}catch(e){setPush("idle");setErr(e.message)}};
const trigger=async()=>{setErr("");try{await setDoc(AREF,{active:true,alertId:`test-${Date.now()}`,type:"test",title:testTitle||"LOW DIESEL STOCK",body:testBody||"PowerHouse diesel alert test.",currentStock:stock??0,lowStockLevel:num(s.lowDieselThreshold),route:"/fuel-management",createdAt:serverTimestamp(),expiresAt:new Date(Date.now()+num(s.alarmDurationSeconds,30)*1000)},{merge:true});setMsg("Real global popup + ring test triggered.")}catch(e){setErr(e.message)}};
const clear=async()=>{try{await setDoc(AREF,{active:false,clearedAt:serverTimestamp()},{merge:true});setMsg("Active alert cleared.")}catch(e){setErr(e.message)}};
return <section className="space-y-5 pb-10"><header className="rounded-[2rem] border border-red-500/20 bg-[#020617] p-5 md:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full border border-red-500/20 bg-red-500/10 px-3 py-1 text-[9px] font-black uppercase tracking-[.2em] text-red-300"><ShieldAlert size={13}/>Protection Control Center</span><h1 className="mt-3 text-3xl font-black md:text-4xl">Diesel Alert & Notification Center</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Live stock protection, popup messages, multiple ring profiles, push notifications and emergency controls.</p></div><button onClick={enable} disabled={push==="loading"} className="inline-flex items-center justify-center gap-2 rounded-xl bg-yellow-500 px-4 py-3 text-xs font-black text-black disabled:opacity-60">{push==="loading"?<RefreshCw size={15} className="animate-spin"/>:<Bell size={15}/>} {push==="enabled"?"Push Enabled":"Enable Push"}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Current Diesel" value={stock===null?"—":stock.toLocaleString()} unit="L" bad={low}/><Stat label="Safety Level" value={num(s.lowDieselThreshold).toLocaleString()} unit="L"/><Stat label="Protection" value={s.enabled?"ACTIVE":"PAUSED"} unit="" good={s.enabled}/><Stat label="Repeat Cycle" value={num(s.repeatMinutes)} unit="min"/></div></header>{err&&<Notice bad>{err}</Notice>}{msg&&<Notice>{msg}</Notice>}{active&&<div className="rounded-2xl border border-red-500/40 bg-red-950/40 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-red-500"><AlertTriangle size={20}/></div><div><p className="text-[9px] font-black uppercase tracking-widest text-red-300">LIVE POPUP ALERT</p><h2 className="font-black text-white">{active.title||"PowerHouse Alert"}</h2><p className="text-sm text-red-100/70">{active.body}</p></div></div><button onClick={clear} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-red-900"><BellRing size={15}/> Clear Alert</button></div></div>}
<div className="grid gap-5 xl:grid-cols-3"><section className="rounded-[1.7rem] border border-white/8 bg-[#020617] p-5 xl:col-span-2"><div className="flex items-center gap-2"><Flame size={18} className="text-red-400"/><h2 className="font-black">Trigger & Ring Controls</h2></div><p className="mt-1 text-xs text-slate-500">All changes sync live to the global alert engine.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Low stock threshold (L)"><input type="number" min="0" value={s.lowDieselThreshold} onChange={e=>setS({...s,lowDieselThreshold:e.target.value})}/></Field><Field label="Repeat interval (min)"><input type="number" min="1" value={s.repeatMinutes} onChange={e=>setS({...s,repeatMinutes:e.target.value})}/></Field><Field label="Ring duration"><select value={s.alarmDurationSeconds} onChange={e=>setS({...s,alarmDurationSeconds:Number(e.target.value)})}>{DURS.map(x=><option key={x} value={x}>{x} seconds</option>)}</select></Field></div><div className="mt-3 flex flex-wrap gap-2">{REPEATS.map(x=><button key={x} onClick={()=>setS({...s,repeatMinutes:x})} className={`rounded-lg px-3 py-2 text-[10px] font-black ${num(s.repeatMinutes)===x?"bg-yellow-500 text-black":"bg-white/5 text-slate-400"}`}>{x} min</button>)}</div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Toggle active={s.enabled} onClick={()=>setS({...s,enabled:!s.enabled})} icon={s.enabled?<CheckCircle2/>:<X/>} title={s.enabled?"Protection enabled":"Protection paused"} text="Automatic low-diesel monitoring"/><Toggle active={!s.silent} onClick={()=>setS({...s,silent:!s.silent})} icon={s.silent?<VolumeX/>:<Volume2/>} title={s.silent?"Silent mode":"Sound enabled"} text="Popup stays visible in silent mode"/><Toggle active={s.pushEnabled} onClick={()=>setS({...s,pushEnabled:!s.pushEnabled})} icon={<Bell/>} title={s.pushEnabled?"Push enabled":"Push disabled"} text="Background device notifications"/></div><button disabled={!changed||saving} onClick={save} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-yellow-500 px-5 py-3 text-xs font-black text-black disabled:opacity-40">{saving?<RefreshCw size={15} className="animate-spin"/>:<Save size={15}/>} Save Global Settings</button></section>
<section className="rounded-[1.7rem] border border-white/8 bg-[#020617] p-5"><div className="flex items-center gap-2"><Volume2 size={18} className="text-emerald-400"/><h2 className="font-black">Ring Profiles</h2></div><p className="mt-1 text-xs text-slate-500">Choose and preview the alert sound.</p><div className="mt-4 space-y-2">{TONES.map(t=><button key={t.id} onClick={()=>setS({...s,alarmTone:t.id})} className={`w-full rounded-xl border p-3 text-left ${s.alarmTone===t.id?"border-yellow-500 bg-yellow-500/10":"border-white/10 bg-white/[.02]"}`}><div className="flex items-center justify-between"><b className="text-xs">{t.name}</b>{s.alarmTone===t.id&&<CheckCircle2 size={15} className="text-yellow-400"/>}</div><p className="mt-1 text-[10px] text-slate-500">{t.desc}</p></button>)}</div><button onClick={()=>s.alarmTone==="custom"&&s.customSoundUrl?new Audio(s.customSoundUrl).play().catch(()=>{}):ring(s.alarmTone)} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-xs font-black text-emerald-300"><Volume2 size={15}/> Preview Selected Ring</button>{s.alarmTone==="custom"&&<input value={s.customSoundUrl} onChange={e=>setS({...s,customSoundUrl:e.target.value})} placeholder="Direct MP3 / OGG / WAV URL" className="mt-3 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-3 text-xs text-white outline-none focus:border-yellow-500"/>}</section></div>
<section className="rounded-[1.7rem] border border-white/8 bg-[#020617] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><BellRing size={18} className="text-red-400"/><h2 className="font-black">Popup Alert Tester</h2></div><p className="mt-1 text-xs text-slate-500">Create a custom test message and trigger the real global popup/ring.</p></div><button onClick={()=>setTester(!tester)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-500 px-4 py-3 text-xs font-black text-white"><BellRing size={15}/> {tester?"Close Tester":"Create Test Popup"}</button></div>{tester&&<div className="mt-4 grid gap-3 md:grid-cols-2"><input value={testTitle} onChange={e=>setTestTitle(e.target.value)} placeholder="Popup title" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none"/><input value={testBody} onChange={e=>setTestBody(e.target.value)} placeholder="Popup message" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none"/><div className="flex flex-wrap gap-2 md:col-span-2"><button onClick={trigger} className="inline-flex items-center gap-2 rounded-xl bg-red-500 px-4 py-3 text-xs font-black text-white">Trigger Live Popup + Ring</button></div></div>}</section>
<section className="rounded-[1.7rem] border border-white/8 bg-[#020617] p-5"><div className="flex items-center gap-2"><Clock3 size={18} className="text-blue-400"/><h2 className="font-black">Recent Alert Events</h2></div><div className="mt-4 divide-y divide-white/5">{events.length?events.map(x=><div key={x.id} className="flex flex-col gap-1 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-white">{x.title||x.type||"PowerHouse Alert"}</p><p className="text-[10px] text-slate-500">{x.body||"—"}</p></div><span className="text-[10px] text-slate-600">{x.createdAt?.toDate?.()?.toLocaleString?.()||"—"}</span></div>):<p className="py-8 text-center text-sm text-slate-600">No alert events yet.</p>}</div></section></section>}
function Stat({label,value,unit,bad,good}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${bad?"text-red-400":good?"text-emerald-400":"text-white"}`}>{value}<small className="ml-1 text-[10px] text-slate-500">{unit}</small></p></div>}
function Field({label,children}){return <label className="block space-y-2"><span className="text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</span>{React.cloneElement(children,{className:"w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm text-white outline-none focus:border-yellow-500"})}</label>}
function Toggle({active,onClick,icon,title,text}){return <button onClick={onClick} className={`flex items-start gap-3 rounded-xl border p-4 text-left ${active?"border-emerald-500/20 bg-emerald-500/[.06]":"border-white/10 bg-white/[.02]"}`}>{React.cloneElement(icon,{size:18,className:active?"text-emerald-400":"text-slate-500"})}<span><b className="block text-xs font-black">{title}</b><small className="text-[10px] text-slate-500">{text}</small></span></button>}
function Notice({children,bad}){return <div className={`rounded-xl border px-4 py-3 text-sm ${bad?"border-red-500/20 bg-red-500/10 text-red-300":"border-emerald-500/20 bg-emerald-500/10 text-emerald-300"}`}>{children}</div>}
