import React,{useCallback,useEffect,useMemo,useRef,useState}from"react";
import{Cable,MapPin,Pencil,RefreshCw,Route,Save,Trash2}from"lucide-react";
import API from"../firebaseApi";import factoryMap from"../assets/factory-map.svg";import PanelDetailsModal from"./PanelDetailsModal";import{mapPosition,routeLengthFeet}from"./panelNetworkUtils";

export default function PanelNetworkEditor(){
 const[panels,setPanels]=useState([]),[routes,setRoutes]=useState([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[mode,setMode]=useState(false);
 const[pts,setPts]=useState([]),[src,setSrc]=useState(""),[dst,setDst]=useState(""),[rid,setRid]=useState(""),[detail,setDetail]=useState(null),[stats,setStats]=useState(null),[search,setSearch]=useState("");
 const[scale,setScale]=useState(()=>{try{return JSON.parse(localStorage.getItem("ph_map_scale"))||{w:100,h:100}}catch{return{w:100,h:100}}});
 const[rf,setRf]=useState({route_code:"",route_name:"",route_type:"cable_tray",cable_size:"",cable_type:"",cable_cores:"",cable_manufacturer:"",cable_voltage_rating:"",tray_type:"",tray_size:"",tray_material:""});
 const mapRef=useRef(null);
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([API.get("/panels"),API.get("/panels/routes/all")]);setPanels(a.data?.panels||[]);setRoutes(b.data?.routes||[])}catch(e){setMsg(e.message||"Could not load panel network.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);useEffect(()=>{localStorage.setItem("ph_map_scale",JSON.stringify(scale))},[scale]);
 const total=useMemo(()=>routes.reduce((s,r)=>s+routeLengthFeet(r.route_points,scale.w,scale.h),0),[routes,scale]),current=routeLengthFeet(pts,scale.w,scale.h);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return panels.filter(p=>!q||[p.panel_code,p.panel_name,p.panel_type,p.area,p.location].filter(Boolean).join(" ").toLowerCase().includes(q))},[panels,search]);
 const source=panels.find(p=>String(p.id)===String(src)),dest=panels.find(p=>String(p.id)===String(dst));
 const open=async p=>{try{const[a,b]=await Promise.all([API.get(`/panels/${p.id}`),API.get(`/panels/${p.id}/stats`)]);setDetail(a.data);setStats(b.data)}catch(e){setMsg(e.message||"Could not load panel details.")}};
 const dragPanel=(e,p)=>{if(mode)return;e.stopPropagation();const map=e.currentTarget.parentElement,move=x=>{const q=mapPosition(x,map);setPanels(a=>a.map(v=>String(v.id)===String(p.id)?{...v,x_position:q.x,y_position:q.y}:v))},up=async x=>{const q=mapPosition(x,map);window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);try{await API.put(`/panels/${p.id}`,{x_position:q.x,y_position:q.y})}catch{load()}};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const mapClick=e=>{if(mode)setPts(a=>[...a,mapPosition(e,e.currentTarget)])};
 const start=()=>{if(!src||!dst||src===dst)return setMsg("Select two different panels.");setPts([{x:+(source?.x_position??50),y:+(source?.y_position??50)},{x:50,y:50},{x:+(dest?.x_position??50),y:+(dest?.y_position??50)}]);setMode(true);setRf(p=>({...p,route_code:p.route_code||`R-${src}-${dst}-${Date.now().toString().slice(-5)}`,route_name:p.route_name||`${source?.panel_code||"Source"} → ${dest?.panel_code||"Destination"}`}))};
 const dragPoint=(e,i)=>{e.stopPropagation();const map=e.currentTarget.parentElement.parentElement,move=x=>{const q=mapPosition(x,map);setPts(a=>a.map((p,k)=>k===i?q:p))},up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const save=async()=>{if(!src||!dst||pts.length<2)return setMsg("Route needs source, destination and at least two points.");try{const p={...rf,source_panel_id:+src,destination_panel_id:+dst,route_points:pts,cable_length:current};if(rid)await API.put(`/panels/routes/${rid}`,p);else await API.post("/panels/routes",p);setMsg(`Route saved: ${current.toFixed(2)} ft`);setMode(false);setPts([]);setRid("");await load()}catch(e){setMsg(e.message||"Could not save route.")}};
 const edit=r=>{setRid(r.id);setSrc(String(r.source_panel_id));setDst(String(r.destination_panel_id));setPts((r.route_points||[]).map(p=>({x:+p.x,y:+p.y})));setRf({...rf,...r});setMode(true)};
 const del=async r=>{if(!confirm(`Delete ${r.route_name||r.route_code}?`))return;await API.delete(`/panels/routes/${r.id}`);await load()};
 return <div className="space-y-5">
  {msg&&<div className="p-3 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 text-xs font-bold">{msg}</div>}
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><h2 className="text-xl font-black text-white">Panel Network & Cable Map</h2><p className="text-slate-500 text-xs mt-1">All existing panels remain visible. Drag markers to update their map position.</p></div><div className="grid grid-cols-2 gap-2 w-full lg:w-72"><label className="text-[9px] text-slate-500 font-black">MAP WIDTH FT<input type="number" min="1" value={scale.w} onChange={e=>setScale(p=>({...p,w:e.target.value}))} className="w-full mt-1 bg-white/5 border border-white/10 rounded-xl p-2.5 text-xs text-white"/></label><label className="text-[9px] text-slate-500 font-black">MAP HEIGHT FT<input type="number" min="1" value={scale.h} onChange={e=>setScale(p=>({...p,h:e.target.value}))} className="w-full mt-1 bg-white/5 border border-white/10 rounded-xl p-2.5 text-xs text-white"/></label></div></div>
  <div className="grid xl:grid-cols-[1fr_390px] gap-5">
   <div><div className="flex gap-2 mb-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search panel, area, location..." className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-xs text-white"/><button type="button" onClick={load} className="p-3 bg-white/5 rounded-xl"><RefreshCw size={15} className={loading?"animate-spin":""}/></button></div>
    <div ref={mapRef} onClick={mapClick} className="relative aspect-[16/10] rounded-2xl overflow-hidden border border-white/10 bg-slate-950 select-none touch-none"><img src={factoryMap} alt="Factory map" className="absolute inset-0 w-full h-full object-contain opacity-75 pointer-events-none"/>
     {routes.map(r=><svg key={r.id} className="absolute inset-0 w-full h-full pointer-events-none"><polyline points={(r.route_points||[]).map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="#22d3ee" strokeWidth="1" vectorEffect="non-scaling-stroke"/></svg>)}
     {mode&&pts.length>1&&<svg className="absolute inset-0 w-full h-full pointer-events-none"><polyline points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="#facc15" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg>}
     {visible.map(p=><button key={p.id} type="button" onClick={e=>{e.stopPropagation();mode?(!src?setSrc(String(p.id)):!dst&&String(p.id)!==String(src)&&setDst(String(p.id))):open(p)}} onPointerDown={e=>dragPanel(e,p)} style={{left:`${p.x_position??50}%`,top:`${p.y_position??50}%`}} className={`absolute -translate-x-1/2 -translate-y-1/2 min-w-9 h-9 px-2 rounded-xl border-2 z-10 shadow-xl flex items-center justify-center gap-1 ${String(p.id)===String(src)||String(p.id)===String(dst)?"bg-yellow-500 text-black border-white":"bg-cyan-500/80 text-white border-cyan-200"}`}><MapPin size={12}/><span className="text-[9px] font-black">{p.panel_code||"P"}</span></button>)}
     {mode&&pts.map((p,i)=><button key={i} type="button" onPointerDown={e=>dragPoint(e,i)} className="absolute w-4 h-4 rounded-full bg-yellow-400 border-2 border-white z-20 -translate-x-1/2 -translate-y-1/2 cursor-grab" style={{left:`${p.x}%`,top:`${p.y}%`}}/>)}{loading&&<div className="absolute inset-0 bg-black/30 flex items-center justify-center"><RefreshCw className="animate-spin text-yellow-500"/></div>}
    </div>
    <div className="grid grid-cols-3 gap-2 mt-3"><div className="p-3 rounded-xl bg-white/5"><p className="text-[9px] text-slate-500 uppercase">Panels</p><b className="text-xl text-white">{panels.length}</b></div><div className="p-3 rounded-xl bg-white/5"><p className="text-[9px] text-slate-500 uppercase">Routes</p><b className="text-xl text-white">{routes.length}</b></div><div className="p-3 rounded-xl bg-yellow-500/10"><p className="text-[9px] text-yellow-500 uppercase">Total Cable</p><b className="text-xl text-white">{total.toFixed(2)} ft</b></div></div>
   </div>
   <div className="space-y-4"><div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10"><div className="flex justify-between"><h3 className="text-white font-black text-sm">Cable Route Builder</h3><Cable size={17} className="text-yellow-500"/></div><div className="grid grid-cols-2 gap-2 mt-3"><select value={src} onChange={e=>setSrc(e.target.value)} className="bg-white/5 border border-white/10 rounded-xl p-2.5 text-xs text-white"><option value="">From panel</option>{panels.map(p=><option key={p.id} value={p.id}>{p.panel_code}</option>)}</select><select value={dst} onChange={e=>setDst(e.target.value)} className="bg-white/5 border border-white/10 rounded-xl p-2.5 text-xs text-white"><option value="">To panel</option>{panels.map(p=><option key={p.id} value={p.id}>{p.panel_code}</option>)}</select></div><button type="button" onClick={start} className="w-full mt-2 py-3 rounded-xl bg-yellow-500 text-black text-xs font-black"><Route size={14} className="inline mr-2"/>Start / Reset Cable</button><div className="grid grid-cols-2 gap-2 mt-3">{["route_code","route_name","cable_size","cable_type","cable_cores","cable_manufacturer","cable_voltage_rating","tray_type","tray_size","tray_material"].map(n=><input key={n} placeholder={n.replaceAll("_"," ")} value={rf[n]||""} onChange={e=>setRf(p=>({...p,[n]:e.target.value}))} className="bg-white/5 border border-white/10 rounded-xl p-2.5 text-xs text-white"/>)}</div><div className="mt-3 p-3 rounded-xl bg-yellow-500/10"><p className="text-[9px] uppercase text-yellow-500 font-black">Live route length</p><b className="text-2xl text-white">{current.toFixed(2)} ft</b><p className="text-[9px] text-slate-500">Each edge updates automatically when a route point is dragged.</p></div><button type="button" onClick={save} disabled={!mode} className="w-full mt-2 py-3 rounded-xl bg-green-500 text-black text-xs font-black disabled:opacity-40"><Save size={14} className="inline mr-2"/>{rid?"Update Route":"Save Route"}</button></div>
    <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10"><div className="flex justify-between mb-2"><h3 className="text-white font-black text-sm">Cable Routes</h3><span className="text-[9px] text-slate-500">{routes.length}</span></div><div className="max-h-72 overflow-auto">{routes.map(r=><div key={r.id} className="py-3 border-b border-white/5"><div className="flex justify-between"><div><b className="text-xs text-white">{r.route_name||r.route_code}</b><p className="text-[9px] text-slate-500">{r.source_panel_code} → {r.destination_panel_code}</p></div><b className="text-xs text-yellow-400">{routeLengthFeet(r.route_points,scale.w,scale.h).toFixed(2)} ft</b></div><div className="flex gap-2 mt-2"><button type="button" onClick={()=>edit(r)} className="px-3 py-2 rounded-lg bg-yellow-500/10 text-yellow-400 text-[9px] font-black"><Pencil size={11} className="inline mr-1"/>Drag/Edit</button><button type="button" onClick={()=>del(r)} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400 text-[9px] font-black"><Trash2 size={11} className="inline mr-1"/>Delete</button></div></div>)}</div></div>
   </div>
  </div>
  <PanelDetailsModal detail={detail} stats={stats} scale={scale} onClose={()=>setDetail(null)}/>
 </div>
}
