import React, { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CalendarClock, Cpu, Gauge, MapPin, RefreshCw, Search, Zap, Wrench, X } from "lucide-react";
import { subscribeToMachineCategories, subscribeToMachineLoadLogs, subscribeToMachines } from "../services/machineService";

const STATUS = { running: ["Running", "text-green-400 bg-green-500/10 border-green-500/20"], standby: ["Standby", "text-blue-400 bg-blue-500/10 border-blue-500/20"], stopped: ["Stopped", "text-slate-400 bg-slate-500/10 border-slate-500/20"], maintenance: ["Maintenance", "text-yellow-400 bg-yellow-500/10 border-yellow-500/20"], out_of_service: ["Out of Service", "text-red-400 bg-red-500/10 border-red-500/20"] };
const today = () => new Date().toISOString().slice(0, 10);
const n = v => Number(v) || 0;
const rangeFor = (period, selected, from, to) => { if (period === "custom") return [from || selected, to || selected]; const d = new Date(`${selected}T00:00:00`); if (period === "monthly") return [new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0,10), new Date(d.getFullYear(), d.getMonth()+1, 0).toISOString().slice(0,10)]; if (period === "weekly") { const s = new Date(d); s.setDate(d.getDate()-d.getDay()); const e = new Date(s); e.setDate(s.getDate()+6); return [s.toISOString().slice(0,10), e.toISOString().slice(0,10)]; } return [selected, selected]; };
const energy = log => n(log.energyConsumed) || n(log.actualLoad) * n(log.operatingHours);

export default function PublicMachines() {
  const [machines,setMachines]=useState([]),[logs,setLogs]=useState([]),[categories,setCategories]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[category,setCategory]=useState("all"),[area,setArea]=useState("all"),[period,setPeriod]=useState("daily"),[date,setDate]=useState(today()),[fromDate,setFromDate]=useState(today()),[toDate,setToDate]=useState(today()),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{setLoading(true);const u=[subscribeToMachines(x=>{setMachines(x);setLoading(false)},e=>{setError(e.message||"Unable to load machines");setLoading(false)}),subscribeToMachineLoadLogs(setLogs,e=>setError(e.message||"Unable to load machine history")),subscribeToMachineCategories(setCategories,e=>setError(e.message||"Unable to load categories"))];return()=>u.forEach(x=>x?.())},[]);
  const cats=useMemo(()=>[...new Set([...categories.map(x=>x.name),...machines.map(x=>x.category)].filter(Boolean))].sort(),[categories,machines]);
  const areas=useMemo(()=>[...new Set(machines.map(x=>x.location).filter(Boolean))].sort(),[machines]);
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return machines.filter(m=>{const hay=[m.name,m.code,m.category,m.type,m.manufacturer,m.model,m.serialNumber,m.location,m.department].filter(Boolean).join(" ").toLowerCase();return(!q||hay.includes(q))&&(status==="all"||(m.status||"standby")===status)&&(category==="all"||m.category===category)&&(area==="all"||m.location===area)})},[machines,search,status,category,area]);
  const [rf,rt]=rangeFor(period,date,fromDate,toDate); const periodLogs=useMemo(()=>logs.filter(l=>String(l.date||"")>=rf&&String(l.date||"")<=rt&&visible.some(m=>m.id===l.machineId)),[logs,rf,rt,visible]);
  const byMachine=useMemo(()=>{const o={};periodLogs.forEach(l=>{o[l.machineId] ||= {energy:0,hours:0,peak:0,records:0};o[l.machineId].energy+=energy(l);o[l.machineId].hours+=n(l.operatingHours);o[l.machineId].peak=Math.max(o[l.machineId].peak,n(l.peakLoad)||n(l.actualLoad));o[l.machineId].records++});return o},[periodLogs]);
  const stats=useMemo(()=>{const rated=visible.reduce((a,m)=>a+n(m.capacity),0),actual=visible.reduce((a,m)=>a+n(m.currentRunningLoad),0),running=visible.filter(m=>m.status==="running").reduce((a,m)=>a+n(m.currentRunningLoad),0);return{total:visible.length,rated,actual,running,energy:periodLogs.reduce((a,l)=>a+energy(l),0),hours:periodLogs.reduce((a,l)=>a+n(l.operatingHours),0),util:rated?(actual/rated)*100:0}},[visible,periodLogs]);
  return <div className="space-y-6"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="w-12 h-12 rounded-2xl bg-yellow-500 text-black flex items-center justify-center"><Cpu size={24}/></div><div><h1 className="text-2xl md:text-3xl font-black">Machines Dashboard</h1><p className="text-slate-500 text-sm">Public read-only machine register, live load and energy analytics</p></div></div><button onClick={()=>window.location.reload()} className="p-3 rounded-xl bg-white/5 border border-white/10 w-fit"><RefreshCw size={18}/></button></div>{error&&<div className="rounded-2xl border border-red-500/20 bg-red-500/10 p-4 text-red-300 text-sm font-bold">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric title="Total Machines" value={stats.total} icon={Cpu}/><Metric title="Rated Load" value={stats.rated.toLocaleString()} unit="kW" icon={Gauge}/><Metric title="Actual Load" value={stats.actual.toLocaleString()} unit="kW" icon={Activity}/><Metric title="Running Load" value={stats.running.toLocaleString()} unit="kW" icon={Zap} tone="green"/></div>
  <div className="grid grid-cols-2 md:grid-cols-3 gap-3"><Metric title="Period Energy" value={stats.energy.toLocaleString(undefined,{maximumFractionDigits:2})} unit="kWh" icon={BarChart3}/><Metric title="Operating Hours" value={stats.hours.toFixed(2)} unit="h" icon={CalendarClock}/><Metric title="Utilization" value={`${stats.util.toFixed(1)}%`} icon={Activity}/></div>
  <section className="rounded-[2rem] border border-white/5 bg-[#020617] p-5"><div className="flex flex-wrap gap-2 mb-5"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select>{period==="custom"?<><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"/></>:<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"/>}<div className="relative flex-1 min-w-[220px]"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search machine, code, manufacturer, area..." className="w-full rounded-xl bg-white/5 border border-white/10 pl-10 pr-3 py-3 text-xs"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"><option value="all">All Statuses</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"><option value="all">All Categories</option>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={area} onChange={e=>setArea(e.target.value)} className="rounded-xl bg-white/5 border border-white/10 px-3 py-3 text-xs"><option value="all">All Areas</option>{areas.map(x=><option key={x}>{x}</option>)}</select></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="border-b border-white/5">{["Machine","Area","Rated Load","Actual Load","Status","Period kWh","Hours","Peak"].map(h=><th key={h} className="px-3 py-3 text-left text-[9px] uppercase tracking-widest text-slate-500">{h}</th>)}</tr></thead><tbody>{visible.map(m=>{const p=byMachine[m.id]||{energy:0,hours:0,peak:0};return <tr key={m.id} className="border-b border-white/[0.04] hover:bg-white/[0.02] cursor-pointer" onClick={()=>setDetail(m)}><td className="px-3 py-4"><p className="font-black text-sm">{m.name||"Unnamed"}</p><p className="text-[9px] text-yellow-500">{m.code||"—"}</p><p className="text-[9px] text-slate-600">{m.category||"General"} · {m.type||"—"}</p></td><td className="px-3 py-4 text-xs text-slate-400"><MapPin size={12} className="inline mr-1"/>{m.location||"—"}</td><td className="px-3 py-4 text-xs font-bold">{n(m.capacity).toLocaleString()} {m.capacityUnit||"kW"}</td><td className="px-3 py-4 text-xs font-bold text-yellow-300">{n(m.currentRunningLoad).toLocaleString()} {m.loadUnit||"kW"}</td><td className="px-3 py-4"><span className={`px-2.5 py-1 rounded-full border text-[9px] font-black uppercase ${STATUS[m.status]?.[1]||STATUS.standby[1]}`}>{STATUS[m.status]?.[0]||"Standby"}</span></td><td className="px-3 py-4 text-xs text-yellow-400 font-black">{p.energy.toFixed(2)}</td><td className="px-3 py-4 text-xs">{p.hours.toFixed(2)}</td><td className="px-3 py-4 text-xs text-orange-300">{p.peak.toFixed(1)}</td></tr>})}</tbody></table>{!loading&&visible.length===0&&<div className="py-14 text-center text-slate-600 font-black">NO MACHINES FOUND</div>}</div></section>
  {detail&&<div className="fixed inset-0 z-[130] bg-black/70 backdrop-blur-sm flex items-center justify-center p-4" onClick={()=>setDetail(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-[2rem] bg-[#020617] border border-white/10 p-6"><div className="flex justify-between"><div><p className="text-yellow-500 text-[9px] font-black uppercase">Machine Details — Read Only</p><h2 className="text-2xl font-black mt-1">{detail.name}</h2><p className="text-slate-500 text-xs">{detail.code} · {detail.location||"No location"}</p></div><button onClick={()=>setDetail(null)} className="p-2 rounded-xl bg-white/5"><X size={18}/></button></div><div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-6">{[["Category",detail.category],["Type",detail.type],["Manufacturer",detail.manufacturer],["Model",detail.model],["Serial Number",detail.serialNumber],["Department",detail.department],["Area / Location",detail.location],["Capacity",`${n(detail.capacity)} ${detail.capacityUnit||"kW"}`],["Current Load",`${n(detail.currentRunningLoad)} ${detail.loadUnit||"kW"}`],["Status",STATUS[detail.status]?.[0]||detail.status],["Installation Date",detail.installDate],["Last Maintenance",detail.lastMaintenance],["Next Maintenance",detail.nextMaintenance]].map(([k,v])=><div key={k} className="rounded-xl bg-white/[0.03] border border-white/5 p-4"><p className="text-[9px] uppercase tracking-widest text-slate-600 font-black">{k}</p><p className="text-sm font-bold mt-1">{v||"—"}</p></div>)}</div>{detail.notes&&<div className="mt-4 rounded-xl bg-white/[0.03] p-4"><p className="text-[9px] uppercase tracking-widest text-slate-600 font-black">Notes</p><p className="text-sm text-slate-300 mt-2 whitespace-pre-wrap">{detail.notes}</p></div>}</div></div>}</div>;
}
function Metric({title,value,unit,icon:Icon,tone="yellow"}){return <div className="rounded-2xl border border-white/5 bg-[#020617] p-5"><div className="flex justify-between"><p className="text-[9px] uppercase tracking-widest text-slate-500 font-black">{title}</p><Icon size={16} className={tone==="green"?"text-green-400":"text-yellow-400"}/></div><p className="mt-2 text-2xl font-black">{value}<span className="text-xs text-slate-500 ml-1">{unit||""}</span></p></div>}
