import React, { useEffect, useState } from "react";
import { Activity, Bell, FileSpreadsheet, Fuel, LayoutDashboard, Zap } from "lucide-react";
import ProductionFuelManagement from "./pages/ProductionFuelManagement";
import DieselAlertNotifications from "./pages/DieselAlertNotifications";
import DieselAlertProV2 from "./pages/DieselAlertProV2";
import FuelManagementLegacy from "./FuelManagement";
import WapdaManagement from "./WapdaManagement";
import DailyDieselReport from "./pages/DailyDieselReportExact";
const TABS=[["dashboard","Dashboard",LayoutDashboard],["entry","Fuel Entry / Fuel Center",Fuel],["alerts","Diesel Alerts",Bell],["wapda","WAPDA Report",Zap],["reports","Fuel Reports",FileSpreadsheet]];
export default function FuelManagementWorkspace(){const[tab,setTab]=useState("dashboard");useEffect(()=>{if(tab!=="dashboard")return;const h=e=>{const b=e.target?.closest?.("button");if(b&&(b.textContent||"").trim().toUpperCase()==="ALERT SETTINGS"){e.preventDefault();e.stopPropagation();setTab("alerts")}};document.addEventListener("click",h,true);return()=>document.removeEventListener("click",h,true)},[tab]);useEffect(()=>{if(tab!=="entry")return;const t=window.setTimeout(()=>{const b=Array.from(document.querySelectorAll("button")).find(x=>x.textContent?.trim()==="Fuel Entry");if(b)b.click()},40);return()=>window.clearTimeout(t)},[tab]);return <div className="fuel-management-workspace min-w-0 space-y-4 pb-8"><style>{`.fuel-management-workspace .fuel-entry-embedded>div>div:first-child>div:first-child{display:none!important}.fuel-management-workspace .fuel-entry-embedded>div>div:first-child{border-radius:1.5rem!important}@media(max-width:640px){.fuel-management-workspace .workspace-nav button{padding:.65rem .8rem;font-size:10px}}`}</style><nav className="workspace-nav sticky top-0 z-30 rounded-2xl border border-white/10 bg-[#020617]/95 p-2 shadow-2xl backdrop-blur-xl"><div className="flex min-w-0 items-center gap-2 overflow-x-auto">{TABS.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-xs font-black transition ${tab===id?"bg-yellow-500 text-black shadow-lg shadow-yellow-500/10":"bg-white/[.04] text-slate-400 hover:bg-white/[.08] hover:text-white"}`}><Icon size={15}/>{label}</button>)}<div className="ml-auto hidden shrink-0 items-center gap-2 px-3 text-[9px] font-black uppercase tracking-[.18em] text-emerald-400 md:flex"><Activity size={13}/> Live Firestore</div></div></nav>{tab==="dashboard"&&<ProductionFuelManagement/>}{tab==="entry"&&<div className="fuel-entry-embedded min-w-0"><FuelManagementLegacy/></div>}{tab==="alerts"&&<DieselAlertProV2/>}{tab==="wapda"&&<WapdaManagement/>}{tab==="reports"&&<DailyDieselReport/>}</div>}
