import { useEffect, useMemo, useRef, useState } from "react";
import { collection, doc, onSnapshot, orderBy, query, limit } from "firebase/firestore";
import { AlertTriangle, Volume2, VolumeX, X, BellOff } from "lucide-react";
import { db } from "./firebase";

const SETTINGS_REF=doc(db,"powerhouse_settings","alerts");
const STATE_REF=doc(db,"powerhouse_alert_state","current");
const DEFAULTS={lowDieselThreshold:3000,repeatMinutes:30,enabled:true,silent:false,alarmDurationSeconds:30,alarmTone:"chime",customSoundUrl:""};
const n=(v,f)=>Number.isFinite(Number(v))?Number(v):f;
const ms=v=>v?.toMillis?.()??(v?new Date(v).getTime():0);
const ACK_KEY="powerhouse-alert-ack-v2";
const readAcks=()=>{try{const raw=JSON.parse(localStorage.getItem(ACK_KEY)||"{}");const now=Date.now();const next={};Object.entries(raw).forEach(([k,v])=>{if(Number(v)>now)next[k]=Number(v)});localStorage.setItem(ACK_KEY,JSON.stringify(next));return next}catch{return{}}};
const writeAck=(id,until)=>{const all=readAcks();all[String(id)]=until;try{localStorage.setItem(ACK_KEY,JSON.stringify(all))}catch{}};
const isAcked=id=>Number(readAcks()[String(id)]||0)>Date.now();
function settings(d={}){return{lowDieselThreshold:Math.max(0,n(d.lowDieselThreshold??d.lowStockLevel,DEFAULTS.lowDieselThreshold)),repeatMinutes:Math.max(1,n(d.repeatMinutes??d.repeatIntervalMinutes,DEFAULTS.repeatMinutes)),enabled:d.enabled!==false&&d.alertsEnabled!==false,silent:d.silent===true||d.silentMode===true,alarmDurationSeconds:Math.min(30,Math.max(20,n(d.alarmDurationSeconds,DEFAULTS.alarmDurationSeconds))),alarmTone:["chime","gentle","pulse","custom"].includes(d.alarmTone)?d.alarmTone:"chime",customSoundUrl:String(d.customSoundUrl||"").trim()}};
export default function GlobalAlertEngine(){
 const[set,setSet]=useState(DEFAULTS),[stock,setStock]=useState(null),[remote,setRemote]=useState(null),[alert,setAlert]=useState(null);
 const ctx=useRef(null),custom=useRef(null),timer=useRef(null),stopTimer=useRef(null),repeat=useRef(null),mounted=useRef(true),sref=useRef(DEFAULTS),stockRef=useRef(null),active=useRef(null);
 const stop=()=>{if(timer.current){clearInterval(timer.current);timer.current=null}if(stopTimer.current){clearTimeout(stopTimer.current);stopTimer.current=null}try{custom.current?.pause();if(custom.current)custom.current.currentTime=0}catch{}try{navigator.vibrate?.(0)}catch{}};
 const acknowledge=(id=active.current,minutes=sref.current.repeatMinutes,remoteAlert=false)=>{if(id)writeAck(id,remoteAlert?Date.now()+Math.max(1,minutes)*60000:Date.now()+Math.max(1,minutes)*60000);stop();active.current=null;if(mounted.current)setAlert(null)};
 const tone=()=>{if(sref.current.silent)return;if(sref.current.alarmTone==="custom"&&sref.current.customSoundUrl){try{if(!custom.current||custom.current.src!==sref.current.customSoundUrl){custom.current=new Audio(sref.current.customSoundUrl);custom.current.volume=.9}void custom.current.play();return}catch{}}
  try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!ctx.current||ctx.current.state==="closed")ctx.current=new C();const c=ctx.current;if(c.state==="suspended")void c.resume();const base=c.currentTime+.02;const notes=sref.current.alarmTone==="gentle"?[[660,0,.28],[880,.34,.32],[784,.78,.34]]:sref.current.alarmTone==="pulse"?[[880,0,.16],[880,.25,.16],[1046,.5,.2],[1046,.82,.25]]:[[784,0,.22],[1046,.28,.25],[880,.62,.24]];notes.forEach(([f,o,d])=>{const osc=c.createOscillator(),g=c.createGain();osc.type="sine";osc.frequency.setValueAtTime(f,base+o);g.gain.setValueAtTime(.0001,base+o);g.gain.exponentialRampToValueAtTime(.72,base+o+.025);g.gain.exponentialRampToValueAtTime(.0001,base+o+d);osc.connect(g);g.connect(c.destination);osc.start(base+o);osc.stop(base+o+d+.04)});navigator.vibrate?.([180,90,180,120,260])}catch(e){console.warn("Low diesel alert tone blocked:",e?.message||e)}};
 const start=()=>{stop();if(sref.current.silent)return;tone();timer.current=setInterval(tone,1700);stopTimer.current=setTimeout(stop,sref.current.alarmDurationSeconds*1000)};
 const notify=async item=>{try{if(Notification.permission!=="granted"||!("serviceWorker"in navigator))return;const r=await navigator.serviceWorker.ready;await r.showNotification(item.title,{body:item.body,icon:"/icon-192.svg",badge:"/icon-192.svg",tag:`powerhouse-alert-${item.alertId}`,renotify:true,requireInteraction:true,silent:sref.current.silent,vibrate:[180,90,180,120,260],data:{route:item.route||"/fuel-management",type:item.type,alertId:item.alertId,currentStock:item.current,lowStockLevel:item.threshold,repeatMinutes:sref.current.repeatMinutes},actions:[{action:"acknowledge",title:"Clear alert"},{action:"view",title:"View dashboard"}]})}catch(e){console.warn("System notification skipped:",e?.message||e)}};
 const activate=item=>{if(!item?.alertId||isAcked(item.alertId))return;active.current=item.alertId;if(mounted.current)setAlert(item);start();void notify(item)};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{if(!("serviceWorker"in navigator))return;const h=e=>{const m=e?.data;if(m?.type==="POWERHOUSE_STOP_ALERT"||m?.type==="POWERHOUSE_ACK_ALERT")acknowledge(m.alertId||active.current,sref.current.repeatMinutes,m?.type==="POWERHOUSE_ACK_ALERT")};navigator.serviceWorker.addEventListener("message",h);return()=>navigator.serviceWorker.removeEventListener("message",h)},[]);
 useEffect(()=>onSnapshot(SETTINGS_REF,s=>{const x=settings(s.exists()?s.data():{});sref.current=x;setSet(x);if(x.silent)stop()},e=>console.warn("Low diesel settings listener failed:",e?.message||e)),[]);
 useEffect(()=>{const q=query(collection(db,"entries"),orderBy("createdAt","desc"),limit(50));return onSnapshot(q,s=>{const x=s.docs[0]?.data(),v=x?n(x.currentStock??x.stock,0):0;stockRef.current=v;setStock(v)},e=>console.warn("Low diesel alert listener failed:",e?.message||e))},[]);
 useEffect(()=>onSnapshot(STATE_REF,s=>{if(!s.exists()){setRemote(null);return}const d=s.data()||{},exp=ms(d.expiresAt);if(d.active===false||(exp&&exp<Date.now())){setRemote(null);return}const id=String(d.alertId||s.id),current=n(d.currentStock??d.stock??stockRef.current,0),threshold=n(d.lowStockLevel??d.lowDieselThreshold??sref.current.lowDieselThreshold,sref.current.lowDieselThreshold);setRemote({alertId:id,title:d.title||"POWERHOUSE ALERT",body:d.body||`Current stock: ${current.toLocaleString()} L`,current,threshold,type:d.type||"manual",route:d.route||"/"})},e=>console.warn("Alert state listener failed:",e?.message||e)),[]);
 const low=useMemo(()=>stock!==null&&set.enabled&&stock<set.lowDieselThreshold,[stock,set.enabled,set.lowDieselThreshold]);
 useEffect(()=>{if(repeat.current){clearInterval(repeat.current);repeat.current=null}if(remote){activate(remote);return}if(!low){if(active.current?.startsWith("low-diesel-"))acknowledge(active.current,0);return}const fire=()=>{const current=n(stockRef.current,0),threshold=sref.current.lowDieselThreshold,id=`low-diesel-${Math.round(threshold)}`;activate({alertId:id,title:"LOW DIESEL STOCK",body:`Current stock: ${current.toLocaleString()} L • Alert level: ${threshold.toLocaleString()} L`,current,threshold,type:"low_diesel",route:"/fuel-management"})};fire();repeat.current=setInterval(fire,Math.max(1,n(sref.current.repeatMinutes,30))*60000);return()=>{if(repeat.current)clearInterval(repeat.current);repeat.current=null}},[low,remote,set.repeatMinutes,set.enabled,set.lowDieselThreshold,set.alarmDurationSeconds]);
 useEffect(()=>()=>{stop();try{void ctx.current?.close?.()}catch{}},[]);
 if(!alert)return null;const clear=()=>acknowledge(alert.alertId,sref.current.repeatMinutes,alert.type==="manual");return <div className="fixed inset-x-3 top-20 z-[300] mx-auto w-auto max-w-xl rounded-2xl border border-red-500/50 bg-red-950/95 p-4 shadow-[0_0_50px_rgba(239,68,68,.3)] backdrop-blur-xl" role="alert"><div className="flex gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-red-500 text-white"><AlertTriangle size={23}/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black tracking-wide text-red-100">{alert.title}</p><p className="mt-1 text-sm text-red-100/80">{alert.body}</p></div><button onClick={clear} className="rounded-lg p-1.5 text-red-100/70 hover:bg-white/10" aria-label="Clear alert and stop ring"><X size={17}/></button></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-red-400/20 bg-black/20 p-3"><p className="text-[10px] font-black uppercase tracking-widest text-red-200/70">Current stock</p><p className="mt-1 text-xl font-black text-white">{Number(alert.current||0).toLocaleString()} L</p></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] font-black uppercase tracking-widest text-red-100/60">Alert level</p><p className="mt-1 text-xl font-black text-red-200">{Number(alert.threshold||0).toLocaleString()} L</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-wider"><span className="rounded-full bg-red-500/20 px-2.5 py-1 text-red-200">{alert.type==="manual"?"Manual admin alert":"Critical operational alert"}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-red-100">Ring {set.alarmDurationSeconds} sec</span>{set.silent?<span className="inline-flex items-center gap-1 text-yellow-300"><VolumeX size={13}/>Silent</span>:<span className="inline-flex items-center gap-1 text-red-100"><Volume2 size={13}/>Sound on</span>}</div><button onClick={clear} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-black text-red-900 hover:bg-red-50"><BellOff size={15}/>Stop ring & clear alert</button></div></div></div>;
}
