import React,{useEffect,useMemo,useRef,useState}from"react";
import factoryMap from"./assets/factory-map.svg";import API from"./firebaseApi";
import{AlertTriangle,Expand,Lock,Map,Minus,Move,Plus,RefreshCw,Search,Unlock,X,Zap}from"lucide-react";
import{mapPoint,readLock,readViewport,writeLock,writeViewport}from"./pages/panelMapUtils";
const STATUS={live:{color:"text-green-400",bg:"bg-green-500/15",icon:Zap},off:{color:"text-red-400",bg:"bg-red-500/15",icon:AlertTriangle},maintenance:{color:"text-yellow-400",bg:"bg-yellow-500/15",icon:AlertTriangle},affected:{color:"text-orange-400",bg:"bg-orange-500/15",icon:AlertTriangle}};
export default function InteractivePanelMap(){
 const[panels,setPanels]=useState([]),[routes,setRoutes]=useState([]),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[moving,setMoving]=useState(false),[locks,setLocks]=useState({}),[fullscreen,setFullscreen]=useState(false);const[viewport,setViewport]=useState(readViewport);const mapRef=useRef(null);const panRef=useRef(null);
 const load=async()=>{setLoading(true);try{const[a,b]=await Promise.all([API.get("/panels"),API.get("/panels/routes/all")]);setPanels(a.data?.panels||[]);setRoutes(b.data?.routes||[])}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{load();const u=API.subscribeToPanels?.(items=>setPanels(items));return()=>u?.()},[]);useEffect(()=>{const x={};panels.forEach(p=>x[p.id]=readLock(p.id));setLocks(x)},[panels]);useEffect(()=>writeViewport(viewport),[viewport]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return panels.filter(p=>!q||[p.panel_code,p.panel_name,p.panel_type,p.area,p.location].filter(Boolean).join(" ").toLowerCase().includes(q))},[panels,search]);
 const zoom=d=>setViewport(v=>({...v,scale:Math.max(.6,Math.min(3,+(v.scale+d).toFixed(2)))}));
 const panStart=e=>{if(moving)return;panRef.current={sx:e.clientX,sy:e.clientY,ox:viewport.x,oy:viewport.y};const move=x=>setViewport(v=>({...v,x:panRef.current.ox+x.clientX-panRef.current.sx,y:panRef.current.oy+x.clientY-panRef.current.sy}));const up=()=>{panRef.current=null;window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const dragPanel=(e,p)=>{if(!moving||locks[p.id])return;e.stopPropagation();const map=e.currentTarget.closest("[data-map]"),move=x=>{const q=mapPoint(x,map);setPanels(a=>a.map(v=>String(v.id)===String(p.id)?{...v,x_position:q.x,y_position:q.y}:v))},up=async x=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);const q=mapPoint(x,map);try{await API.put(`/panels/${p.id}`,{x_position:q.x,y_position:q.y})}catch{load()}};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const toggleLock=p=>{const n=!locks[p.id];writeLock(p.id,n);setLocks(a=>({...a,[p.id]:n}))};
 return <div className="space-y-5"><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-yellow-500 text-black flex items-center justify-center"><Map size={24}/></div><div><h2 className="text-xl md:text-2xl font-black text-white">Interactive Panel Map</h2><p className="text-slate-500 text-xs">Drag, lock, zoom, pan and inspect the electrical network.</p></div></div><div className="flex flex-wrap gap-2"><div className="relative flex-1 min-w-[180px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search panel" className="w-full bg-white/5 border border-white/10 rounded-xl pl-9 pr-3 py-2.5 text-xs text-white outline-none"/></div><button onClick={load} className="p-3 bg-white/5 border border-white/10 rounded-xl"><RefreshCw size={16} className={loading?"animate-spin":""}/></button><button onClick={()=>setMoving(v=>!v)} className={`p-3 rounded-xl border ${moving?"bg-yellow-500 text-black":"bg-white/5 text-white border-white/10"}`} title="Move panels"><Move size={16}/></button><button onClick={()=>setFullscreen(v=>!v)} className="p-3 bg-white/5 border border-white/10 rounded-xl"><Expand size={16}/></button></div></div>
 <div className={`${fullscreen?"fixed inset-3 z-[80]":"relative"} bg-[#020617] border border-white/10 rounded-3xl overflow-hidden`}><div className="absolute z-30 top-3 left-3 flex gap-2"><button onClick={()=>zoom(.15)} className="p-2.5 rounded-xl bg-black/70 border border-white/10"><Plus size={16}/></button><button onClick={()=>zoom(-.15)} className="p-2.5 rounded-xl bg-black/70 border border-white/10"><Minus size={16}/></button><button onClick={()=>setViewport({scale:1,x:0,y:0})} className="px-3 py-2.5 rounded-xl bg-black/70 border border-white/10 text-[10px] font-black">Reset</button></div><div className="absolute z-30 top-3 right-3 px-3 py-2 rounded-xl bg-black/70 border border-white/10 text-[10px] text-slate-300">{moving?"MOVE MODE":"PAN MODE"} • {Math.round(viewport.scale*100)}%</div>
 <div data-map ref={mapRef} onPointerDown={panStart} className={`${fullscreen?"h-[calc(100vh-24px)]":"h-[520px] md:h-[650px]"} relative bg-slate-950 select-none touch-none overflow-hidden`}><div className="absolute inset-0" style={{transform:`translate(${viewport.x}px,${viewport.y}px) scale(${viewport.scale})`,transformOrigin:"center"}}><img src={factoryMap} alt="Factory map" className="absolute inset-0 w-full h-full object-contain opacity-70 pointer-events-none"/>{routes.map(r=><svg key={r.id} viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 w-full h-full pointer-events-none"><polyline points={(r.route_points||[]).map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="#22d3ee" strokeWidth="1" vectorEffect="non-scaling-stroke"/></svg>)}{visible.map(p=>{const s=String(p.effective_status||p.status||"live").toLowerCase(),c=STATUS[s]||STATUS.live,I=c.icon;return <button key={p.id} type="button" title={p.panel_name} onPointerDown={e=>dragPanel(e,p)} onClick={e=>{e.stopPropagation();if(!moving)setSelected(p)}} style={{left:`${Number(p.x_position??50)}%`,top:`${Number(p.y_position??50)}%`}} className={`absolute -translate-x-1/2 -translate-y-1/2 min-w-9 min-h-9 px-2 rounded-xl ${c.bg} ${c.color} border-2 ${locks[p.id]?"border-yellow-400":"border-white/20"} shadow-xl flex items-center justify-center gap-1 z-20 ${moving?(locks[p.id]?"cursor-not-allowed":"cursor-grab"):"cursor-pointer"}`}><I size={13}/><span className="text-[9px] font-black max-w-24 truncate">{p.panel_code||"P"}</span></button>})}</div>{loading&&<div className="absolute inset-0 bg-black/20 flex items-center justify-center"><RefreshCw className="animate-spin text-yellow-500"/></div>}</div>
 <div className="absolute z-30 bottom-3 left-3 right-3 flex flex-wrap justify-between gap-2"><div className="flex gap-2">{selected&&<><button onClick={()=>toggleLock(selected)} className="px-3 py-2 rounded-xl bg-black/75 border border-white/10 text-xs">{locks[selected.id]?<Unlock size={13} className="inline mr-1"/>:<Lock size={13} className="inline mr-1"/>}{locks[selected.id]?"Unlock":"Lock"}</button><button onClick={()=>setSelected(null)} className="px-3 py-2 rounded-xl bg-black/75 border border-white/10 text-xs"><X size={13} className="inline mr-1"/>Close</button></>}</div><div className="px-3 py-2 rounded-xl bg-black/75 border border-white/10 text-[10px] text-slate-300">{visible.length} panels • {routes.length} routes</div></div></div>
 {selected&&<div className="fixed inset-0 z-[90] bg-black/80 p-4 overflow-auto" onClick={()=>setSelected(null)}><div className="max-w-2xl mx-auto my-8 bg-[#07101f] border border-white/10 rounded-3xl p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-yellow-500 text-xs font-black">{selected.panel_code}</p><h3 className="text-2xl font-black">{selected.panel_name}</h3></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-5">{[["Type",selected.panel_type],["Status",selected.status],["Voltage",selected.voltage],["Rated Current",selected.rated_current],["Manufacturer",selected.manufacturer],["Model",selected.model]].map(([k,v])=><div key={k} className="p-3 bg-white/5 rounded-xl"><p className="text-[9px] text-slate-500 uppercase font-black">{k}</p><p className="text-sm font-bold mt-1 break-words">{v||"N/A"}</p></div>)}</div></div></div>}</div>;
}
