import { useEffect, useRef, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth, getFCMToken, onForegroundMessage } from "./firebase";
import { subscribeToNotifications } from "./services/notificationService";
import { socket } from "./utils/socket";

const TASK_EVENTS = new Set(["taskAssigned","taskReassigned","taskUpdate","taskUpdated","taskEdited","taskDeleted","taskDelete","taskAccepted","taskRejected","taskCompleted","taskStatusChanged"]);
const priorityLabel = (v) => { const p = String(v || "").toLowerCase(); return ({low:"Low",medium:"Medium",high:"High",critical:"Critical",urgent:"Critical"})[p] || "Medium"; };
const taskText = (event, data = {}) => { const task = data.task || data; const rawTitle = String(task.title || task.taskTitle || data.notificationTitle || data.title || "").trim(); const priority = priorityLabel(task.priority || task.type || data.priority || data.taskType); const labels = {taskAssigned:"New task assigned",taskReassigned:"Task reassigned",taskUpdate:"Task updated",taskUpdated:"Task updated",taskEdited:"Task updated",taskDeleted:"Task deleted",taskDelete:"Task deleted",taskAccepted:"Task accepted",taskRejected:"Task rejected",taskCompleted:"Task completed",taskStatusChanged:"Task status changed"}; const title = rawTitle ? `${labels[event] || "Task notification"}: ${rawTitle}` : (labels[event] || "PowerHouse Task Alert"); const body = String(data.body || data.message || task.description || `Priority: ${priority}`).trim(); return {title, body: body.includes("Priority:") ? body : `${body} • Priority: ${priority}`}; };
const routeFor = (data = {}) => String(data.route || "").trim() || (data.taskId || data.task_id || data.id ? `/task-view/${data.taskId || data.task_id || data.id}` : "/notifications");
const userIds = (u) => [u?.uid,u?.numericId,u?.id].filter((v)=>v!==undefined&&v!==null&&String(v).trim()).map(String);
const recipients = (d={}) => { const v=d.userIds??d.user_ids??d.userId??d.user_id??d.assignedTo??d.assigned_to; return Array.isArray(v)?v.map(String):v===undefined||v===null?[]:[String(v)]; };

export default function NotificationRuntime(){
 const [alert,setAlert]=useState(null); const audioRef=useRef(null), timerRef=useRef(null), seenRef=useRef(new Map());
 useEffect(()=>{ let disposed=false, offAuth=()=>{}, offMsg=()=>{}, offNotes=()=>{}, offSocket=()=>{}, refreshTimer=null;
  const unlock=async()=>{ try{ const C=window.AudioContext||window.webkitAudioContext; if(!C)return; if(!audioRef.current)audioRef.current=new C(); if(audioRef.current.state==="suspended")await audioRef.current.resume(); }catch{} };
  const ring=async()=>{ try{ await unlock(); const c=audioRef.current;if(!c||c.state!=="running")return; const t=c.currentTime; [[988,0,.22],[740,.25,.22],[988,.5,.22],[740,.75,.22],[988,1,.32]].forEach(([f,o,d])=>{const osc=c.createOscillator(),g=c.createGain();osc.frequency.value=f;g.gain.setValueAtTime(.0001,t+o);g.gain.exponentialRampToValueAtTime(.7,t+o+.02);g.gain.exponentialRampToValueAtTime(.0001,t+o+d);osc.connect(g);g.connect(c.destination);osc.start(t+o);osc.stop(t+o+d+.03);}); navigator.vibrate?.([350,120,350,120,500]); }catch{} };
  const show=async(title,body,route="/notifications",id="")=>{ if(disposed)return; const key=String(id||`${title}|${body}|${route}`); const now=Date.now(), old=seenRef.current.get(key); if(old&&now-old<4000)return; seenRef.current.set(key,now); for(const [k,v] of seenRef.current)if(now-v>30000)seenRef.current.delete(k); try{navigator.setAppBadge?.(1)}catch{}; setAlert({title,body,route}); clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>setAlert(null),15000);void ring(); try{if(Notification.permission==="granted"&&"serviceWorker" in navigator){const r=await navigator.serviceWorker.ready;await r.showNotification(title,{body,icon:"/icon-192.svg",badge:"/icon-192.svg",tag:key,renotify:true,requireInteraction:true,silent:false,vibrate:[350,120,350,120,500],data:{route,notificationId:key}})}}catch{} };
  const registerPush=async(prompt=false)=>{ if(!auth.currentUser)return; try{await getFCMToken({requestPermission:prompt,forceFresh:false});}catch{} };
  const setup=async(user)=>{ offMsg();offNotes();offSocket();if(!user||disposed)return; await registerPush(true); refreshTimer=setInterval(()=>void registerPush(false),15*60*1000);
   try{offMsg=await onForegroundMessage((p)=>{const d=p?.data||{};const text=taskText("taskAssigned",{...d,title:p?.notification?.title||d.title,body:p?.notification?.body||d.body});void show(text.title,text.body,routeFor(d),d.notificationId||p.messageId);});}catch{}
   let initial=true; offNotes=subscribeToNotifications(user.uid,(items)=>{ if(initial){initial=false;return;} for(const n of items.filter(x=>!x.read).slice(0,5)){ const text=taskText("taskAssigned",n);void show(text.title,text.body,n.route||routeFor(n),n.id); } });
   if(socket){const ids=userIds(user),join=()=>{ids.forEach(id=>socket.emit("joinUser",id));}; if(socket.connected)join();socket.on("connect",join);const any=(event,data={})=>{if(!TASK_EVENTS.has(event))return;const r=recipients(data);if(r.length&&!r.some(id=>ids.includes(id)))return;const text=taskText(event,data);void show(text.title,text.body,routeFor(data),data.notificationId||`${event}-${data.taskId||data.id||Date.now()}`);};socket.onAny(any);offSocket=()=>{socket.off("connect",join);socket.offAny(any);};}
  };
  offAuth=onAuthStateChanged(auth,u=>void setup(u)); const gesture=()=>void unlock(); const visible=()=>{if(document.visibilityState==="visible")void registerPush(false)}; window.addEventListener("pointerdown",gesture,{passive:true});window.addEventListener("keydown",gesture);document.addEventListener("visibilitychange",visible);
  return()=>{disposed=true;offAuth();offMsg();offNotes();offSocket();clearInterval(refreshTimer);clearTimeout(timerRef.current);window.removeEventListener("pointerdown",gesture);window.removeEventListener("keydown",gesture);document.removeEventListener("visibilitychange",visible);try{audioRef.current?.close?.()}catch{}};
 },[]);
 if(!alert)return null; return <button type="button" onClick={()=>{try{navigator.clearAppBadge?.()}catch{};window.location.href=alert.route;}} className="fixed right-4 top-24 z-[200] w-[min(92vw,420px)] rounded-2xl border border-yellow-500/30 bg-[#020617]/95 p-4 text-left shadow-2xl backdrop-blur-xl" aria-label="Open notification"><div className="flex items-start gap-3"><div className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-yellow-500 text-black">🔔</div><div className="min-w-0"><p className="text-sm font-black text-white">{alert.title}</p><p className="mt-1 text-sm leading-5 text-slate-300">{alert.body}</p><p className="mt-2 text-[10px] font-black uppercase tracking-widest text-yellow-500">Open task</p></div></div></button>;
}